Repository kruize/kruize, pull requests merged in 2019-12, with the labels that each got.

#30 Improve logging
  docs/README.md
  manifests/kruize.yaml_template
  pom.xml
  src/main/java/com/kruize/analysis/Analysis.java
  src/main/java/com/kruize/analysis/AnalysisImpl.java
  src/main/java/com/kruize/collection/CollectMetrics.java
  src/main/java/com/kruize/environment/Defaults.java
  src/main/java/com/kruize/environment/docker/DockerDefaults.java
  src/main/java/com/kruize/environment/docker/DockerEnvImpl.java
  src/main/java/com/kruize/environment/kubernetes/KubernetesDefaults.java
  src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java
  src/main/java/com/kruize/initialize/Initialize.java
  src/main/java/com/kruize/main/Kruize.java
  src/main/java/com/kruize/metrics/AbstractMetrics.java
  src/main/java/com/kruize/recommendations/application/AbstractApplicationRecommendations.java
  src/main/java/com/kruize/util/HttpUtil.java
  src/main/java/com/kruize/util/MathUtil.java
  src/main/resources/log4j2.properties
Labels: enhancement

#67 Add openshift deploy documentation.
  docs/README.md
Labels: documentation

#69 build.sh should take image name as a parameter.
  build.sh
  manifests/kruize.yaml_template
  scripts/icp-helpers.sh
  scripts/minikube-helpers.sh
  scripts/openshift-helpers.sh
Labels: enhancement

#68 Included a travis test to validate kruize deployment
  .travis.yml
Labels: enhancement

#72 Run the travis checks on all branches.
  .travis.yml
  scripts/build_sanity_test.sh
Labels: bug

#77 deploy.sh should handle errors gracefully
  scripts/icp-helpers.sh
  scripts/minikube-helpers.sh
  scripts/openshift-helpers.sh
Labels: bug
